version: "3.9"

services:
  db:
    #image: postgres:15
    build:
      context: ./portfolio_db
      dockerfile: dockerfile
    container_name: my_postgres
    env_file:
      - ./docker.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build:
      context: . #https://gitea.bocktank.com/abock/portfolio-site.git
      dockerfile: Dockerfile
    container_name: my_app
    depends_on:
      - db
    ports:
      - "8086:8080"
    environment:
      - JWT_SECRET_FILE=/run/secrets/jwt_secret
    volumes:
      - ./backend/static:/app/static
    restart: on-failure
    secrets:
      - jwt_secret



secrets:
  jwt_secret:
    file: ./jwt_secret.txt
