version: "3.9"

services:
  db:
    #image: postgres:15
    build: 
      context: ./portfolio_db
      dockerfile: dockerfile
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build:
      context: . #https://gitea.bocktank.com/abock/portfolio-site.git
      dockerfile: Dockerfile
    container_name: my_app
    depends_on:
      - db
    ports:
      - "8080:8080"
  #  volumes:
   #   - ./backend/static:/app/static
    restart: on-failure

volumes:
  pgdata:
